### ISSUE TITLE
Parameters aren't labelled in created widget

### ISSUE THREAD

**Issue by Saerith** [BioDepot/BioDepot-workflow-builder#12]
After creating a widget with multiple required parameters and going to run the widget, the parameter textfields give no indication which belongs to which attribute, it just says "enter parameter". I just happen to know the order it's in in JSON, but it really should have perhaps some hint-text that says the parameter's name, "filename" or "timeout" or what have you.

![image](https://user-images.githubusercontent.com/8922534/43513692-451dad4c-9533-11e8-9b79-9f3449688397.png)

**Comment by lhhunghimself** [comment]
You can add a Label next to the field by entering it in the label field when using the WidgetBuilder....

There is no current way to change the grayed text - I do plan to add that later but if you have a label it's not so bad...
