### ISSUE TITLE
Install packages like papermill

### ISSUE THREAD

**Issue by pushkarbajaj9** [BioDepot/BioDepot-workflow-builder#17]
How to install and use new packages like papermill using the existing widgets? 
I installed the package in the container using bash and it did work through terminal but the bash_util widget doesn't recognise it. How do I install papermill so that the bash_util supports that as well?

**Comment by lhhunghimself** [comment]
You can install packages in the Bwb container using the terminal as it is essentially an Ubuntu VM which is what it appears you did.

The widgets however, run their own container. So the Bash widget actually runs a very small alpine based container. If you drag the widget onto the canvas and right click on it you will see the container that it uses. This container is designed to run simple Bash scripts. You can create a new container to have papermill in it and then create a new widget to run this. Then you would define the command to be run by the widget, what flags are to be exposed to the user, and any inputs/outputs that you want to allow the papermill widget to connect to other widgets. This is all done using the screens that you see when right clicking on an existing widget or using the create new widget option. 

There is a tutorial in the manual and a video which guides you through modifying the widget. However, you will have to build the papermill container or find one on DockerHub.
