### ISSUE TITLE
no option to set bool flag (true/false) when it is set as an optional parameter

### ISSUE THREAD

**Issue by rgschmitz1** [BioDepot/BioDepot-workflow-builder#27]
There should be one box to enable the optional argument and another to set as true/false.

**Comment by lhhunghimself** [comment]
If you wanted to do this you could just pass a string. What we really need is a  restricted type i.e. restricted to one out of a list of choices which could be True/False or red/green/blue. This is something that is relatively easy to implement and will do next round of upgrades.

**Comment by rgschmitz1** [comment]
Using a string sounds fine to me, I suppose 'True/False' can differ depending on the language you're using too.

**Comment by lhhunghimself** [comment]
You can also pass the boolean as an environment variable, check if it is set or not and then add the appropriate flag string in a wrapper.
