### ISSUE TITLE
TypeError when adding new widget from existing widget

### ISSUE THREAD

**Issue by BryceNoFu** [BioDepot/BioDepot-workflow-builder#32]
### Purpose
To build a new widget using an existing widget. This option is accessed using the Widget section of the toolbar.

### Issue
Error in Widget Builder states a TypeError occurs, cannot create widget.

### Procedure that leads to the error
![f7805304803390e862a7d8cc029df761](https://user-images.githubusercontent.com/38656368/109575377-88032780-7aa6-11eb-92c7-f1d50ae6b607.gif)

A second type of error message appears when attempting a second time:
![TypeError](https://user-images.githubusercontent.com/38656368/109576016-d49b3280-7aa7-11eb-944d-a8179c1aedba.png)

**Comment by lhhunghimself** [comment]
Fixed.

The bug occurs with a new widget when checking to see if the same widget is being used as a template. For new widgets the new directory does not yet exist. This also means that it can't be the same widget as the template so adding a check that the directory exists does not change the logic.

**Comment by rgschmitz1** [comment]
This issue is still present in the latest version of Bwb.
