### ISSUE TITLE
Required and optional parameters are not passed to container when command field is left empty

### ISSUE THREAD

**Issue by rgschmitz1** [BioDepot/BioDepot-workflow-builder#33]
**Issue**
I was testing a container with an entrypoint so I left the command field blank.  Leaving the command field blank results in required and optional parameters not being passed along to the container.

**To recreate**
Create a widget with docker image (e.g. 'biodepot/igv' tag 'latest'), remove all input from command field.  Input an optional or required parameter to pass to the container (e.g. bam file).

**Comment by rgschmitz1** [comment]
#34 Should resolve this issue.

**Comment by lhhunghimself** [comment]
Can you resubmit this - I think I closed this before merging

Hong
