### ISSUE TITLE
Add option to enable/disable VNC disconnect

### ISSUE THREAD

**Issue by rgschmitz1** [BioDepot/BioDepot-workflow-builder#39]
Bwb noVNC seems to disconnect randomly after some time has passed and cannot be reconnected, this isn't ideal for longer workflows (1 day plus).  If there is an option to disable the idle disconnect feature it should be disabled by default and turned on via a flag if desired.

![image](https://user-images.githubusercontent.com/14095796/119551040-05f56880-bd4e-11eb-9bf5-82d4e693c1bd.png)

**Comment by lhhunghimself** [comment]
I think this has been fixed with the nginx timeout increase.
