### ISSUE TITLE
Bwb new widget from template issue

### ISSUE THREAD

**Issue by rgschmitz1** [BioDepot/BioDepot-workflow-builder#42]
Issue #32 is still present but the error message seems to have changed slightly.  Instructions from #32 can be followed to recreate this error.
![image](https://user-images.githubusercontent.com/14095796/120693475-e6e98b80-c45d-11eb-9a6f-ae7433a0e77c.png)

**Comment by lhhunghimself** [comment]
Initialized undefined widgetDir which fixes problem.
