### ISSUE TITLE
Dockerfiles not copied when creating new widget and using SaveAs

### ISSUE THREAD

**Issue by rgschmitz1** [BioDepot/BioDepot-workflow-builder#44]
When creating a new widget from template, the Dockerfiles directory has it's contents copied to "/templates/Generic/Dockerfiles".  
The Dockerfiles are never copied to the new directory when using the "Save As" button, but I'm not sure this is intentional (i.e. Dockerfiles should probably be copied to the new widget directory?)

**Comment by lhhunghimself** [comment]
Let me check this out. It looks like a real bug.
