### ISSUE TITLE
Default user-defined widget values

### ISSUE THREAD

**Issue by Saerith** [BioDepot/BioDepot-workflow-builder#8]
There are a number of fields in the widget builder that are currently required that may have default values.
The `icon` field is required and has no default. There is a 'default' user icon in biodepot/User/icons.
Is a `description` required?
Is a value required for `priority`?

**Comment by lhhunghimself** [comment]
I'm in the process of fixing this. There is now a default name and icon. There is a default priority as well that  the orange engine uses that could be used for the priority. This is just used to order the widgets in the toolbox - and I will change the form label to make that clearer
