### ISSUE TITLE
Docker cannot run shell scripts with Windows crlf on Linux

### ISSUE THREAD

**Issue by Saerith** [BioDepot/BioDepot-workflow-builder#9]
The two shell scripts after building contain Windows style line endings, which on Linux gives the error `/bin/sh: /startup.sh: /bin/bash^M: bad interpreter: No such file or directory`. A .gitattributes file should be added to set text or shell scripts to `eol=lf` and all crlf need replaced.

**Comment by Saerith** [comment]
Wild, I don't use git on Windows ever. I avoid developing on it as much as
possible. I wonder how that happened when I pulled? I'll check my settings
again.

**Comment by lhhunghimself** [comment]
Added .gitattributes to override user settings and prevent this in the future.
